# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allCount <- function(x) {
    .Call('_diveRsity_allCount', PACKAGE = 'diveRsity', x)
}

bsHetCalc <- function(af) {
    .Call('_diveRsity_bsHetCalc', PACKAGE = 'diveRsity', af)
}

diffCalcHarm <- function(idt, pw) {
    .Call('_diveRsity_diffCalcHarm', PACKAGE = 'diveRsity', idt, pw)
}

expHet <- function(af) {
    .Call('_diveRsity_expHet', PACKAGE = 'diveRsity', af)
}

genos2mat <- function(mat, ip, na) {
    .Call('_diveRsity_genos2mat', PACKAGE = 'diveRsity', mat, ip, na)
}

glbWCcpp <- function(hsum, af, indtyp) {
    .Call('_diveRsity_glbWCcpp', PACKAGE = 'diveRsity', hsum, af, indtyp)
}

hweTab <- function(af) {
    .Call('_diveRsity_hweTab', PACKAGE = 'diveRsity', af)
}

myTab <- function(x) {
    .Call('_diveRsity_myTab', PACKAGE = 'diveRsity', x)
}

obsHet <- function(in_mat) {
    .Call('_diveRsity_obsHet', PACKAGE = 'diveRsity', in_mat)
}

pwHCalc <- function(af, sHarm, pw) {
    .Call('_diveRsity_pwHCalc', PACKAGE = 'diveRsity', af, sHarm, pw)
}

pwHt <- function(af, pw) {
    .Call('_diveRsity_pwHt', PACKAGE = 'diveRsity', af, pw)
}

pwTabMerge <- function(hsum, pw) {
    .Call('_diveRsity_pwTabMerge', PACKAGE = 'diveRsity', hsum, pw)
}

pwWCcpp <- function(hsum1, af1, indtyp1, pw) {
    .Call('_diveRsity_pwWCcpp', PACKAGE = 'diveRsity', hsum1, af1, indtyp1, pw)
}

Tab <- function(x) {
    .Call('_diveRsity_Tab', PACKAGE = 'diveRsity', x)
}

tabMerge <- function(hsum) {
    .Call('_diveRsity_tabMerge', PACKAGE = 'diveRsity', hsum)
}

varFunc <- function(af, sHarm) {
    .Call('_diveRsity_varFunc', PACKAGE = 'diveRsity', af, sHarm)
}

