# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glbWCcpp <- function(hsum, af, indtyp) {
    .Call('diveRsity_glbWCcpp', PACKAGE = 'diveRsity', hsum, af, indtyp)
}

myTab <- function(x) {
    .Call('diveRsity_myTab', PACKAGE = 'diveRsity', x)
}

pwHCalc <- function(af, sHarm, pw) {
    .Call('diveRsity_pwHCalc', PACKAGE = 'diveRsity', af, sHarm, pw)
}

pwHt <- function(af, pw) {
    .Call('diveRsity_pwHt', PACKAGE = 'diveRsity', af, pw)
}

pwWCcpp <- function(hsum1, af1, indtyp1, pw) {
    .Call('diveRsity_pwWCcpp', PACKAGE = 'diveRsity', hsum1, af1, indtyp1, pw)
}

varFunc <- function(af, sHarm) {
    .Call('diveRsity_varFunc', PACKAGE = 'diveRsity', af, sHarm)
}

