# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Tab <- function(x) {
    .Call(`_diveRsity_Tab`, x)
}

allCount <- function(x) {
    .Call(`_diveRsity_allCount`, x)
}

bsHetCalc <- function(af) {
    .Call(`_diveRsity_bsHetCalc`, af)
}

diffCalcHarm <- function(idt, pw) {
    .Call(`_diveRsity_diffCalcHarm`, idt, pw)
}

expHet <- function(af) {
    .Call(`_diveRsity_expHet`, af)
}

genos2mat <- function(mat, ip, na) {
    .Call(`_diveRsity_genos2mat`, mat, ip, na)
}

glbWCcpp <- function(hsum, af, indtyp) {
    .Call(`_diveRsity_glbWCcpp`, hsum, af, indtyp)
}

hweTab <- function(af) {
    .Call(`_diveRsity_hweTab`, af)
}

myTab <- function(x) {
    .Call(`_diveRsity_myTab`, x)
}

obsHet <- function(in_mat) {
    .Call(`_diveRsity_obsHet`, in_mat)
}

pwHCalc <- function(af, sHarm, pw) {
    .Call(`_diveRsity_pwHCalc`, af, sHarm, pw)
}

pwHt <- function(af, pw) {
    .Call(`_diveRsity_pwHt`, af, pw)
}

pwTabMerge <- function(hsum, pw) {
    .Call(`_diveRsity_pwTabMerge`, hsum, pw)
}

pwWCcpp <- function(hsum1, af1, indtyp1, pw) {
    .Call(`_diveRsity_pwWCcpp`, hsum1, af1, indtyp1, pw)
}

tabMerge <- function(hsum) {
    .Call(`_diveRsity_tabMerge`, hsum)
}

varFunc <- function(af, sHarm) {
    .Call(`_diveRsity_varFunc`, af, sHarm)
}

